### PR TITLE
Use Javascript and CSS libraries from CDN instead of bundling local copies

### PR DESCRIPTION
**Pull request by Sanrag**

### CODE REVIEW

**Comment by matttproud** [comment]
My feelings for this cut both ways.  Assuming CDN access for an industrial tool seems like a bit much, but don't let my vote be a blocker.

**Comment by Sanrag** [comment]
My primary motivation was not having to deal with licensing issues as we were bundling the libraries in the JAR. (Do we bundle the licenses too? Does version upgrade change the license? etc.)
I'm OK if we want to keep the dependencies local.

**Comment by matttproud** [comment]
Good point!  The versions for these dependencies should be penned, so I don't think we'd expect them to change out from under us, though.

**Comment by Sanrag** [comment]
Yup, they are pinned. The only reason we would upgrade is to have a new feature not supported by current version (and maybe, security !)

**Comment by matttproud** [comment]
@Sanrag LGTM

**Pull request merged**
